using System;
using System.Collections.Generic;
using System.Text;

namespace ICD.Connect.Krang.SPlus.Routing.Endpoints.Sources
{
	public static class KrangAtHomeSourceIconExtensions
	{
		private const string TRANSPARENT_ICON_SERIAL = "si_blank";

		private static readonly Dictionary<eKrangAtHomeSourceIcon, string> s_IconSerials = new Dictionary
			<eKrangAtHomeSourceIcon, string>
		{
			{eKrangAtHomeSourceIcon.AddressBook, "addressBook"},
			{eKrangAtHomeSourceIcon.Airplay, "airplay"},
			{eKrangAtHomeSourceIcon.Alarm, "alarm"},
			{eKrangAtHomeSourceIcon.Alert, "alert"},
			{eKrangAtHomeSourceIcon.Android, "android"},
			{eKrangAtHomeSourceIcon.Apple, "apple"},
			{eKrangAtHomeSourceIcon.AudioNote, "audioNote"},
			{eKrangAtHomeSourceIcon.Ban, "ban"},
			{eKrangAtHomeSourceIcon.Bluetooth, "bluetooth"},
			{eKrangAtHomeSourceIcon.BluRay, "blu-ray"},
			{eKrangAtHomeSourceIcon.Bolt, "bolt"},
			{eKrangAtHomeSourceIcon.Bowling, "bowling"},
			{eKrangAtHomeSourceIcon.BrightnessLight, "brightnessLight"},
			{eKrangAtHomeSourceIcon.BrightnessMax, "brightnessMax"},
			{eKrangAtHomeSourceIcon.BrightnessMedium, "brightnessMedium"},
			{eKrangAtHomeSourceIcon.Brush, "brush"},
			{eKrangAtHomeSourceIcon.Calendar, "calendar"},
			{eKrangAtHomeSourceIcon.Camera, "camera"},
			{eKrangAtHomeSourceIcon.Cart, "cart"},
			{eKrangAtHomeSourceIcon.Cd, "cd"},
			{eKrangAtHomeSourceIcon.Check, "check"},
			{eKrangAtHomeSourceIcon.Checkbox, "checkbox"},
			{eKrangAtHomeSourceIcon.CheckboxChecked, "checkedCheckbox"},
			{eKrangAtHomeSourceIcon.Clickshare, "clickshare"},
			{eKrangAtHomeSourceIcon.Climate, "climate"},
			{eKrangAtHomeSourceIcon.Clock, "clock"},
			{eKrangAtHomeSourceIcon.Comment, "comment"},
			{eKrangAtHomeSourceIcon.CommentCheck, "commentCheck"},
			{eKrangAtHomeSourceIcon.Connector, "connector"},
			{eKrangAtHomeSourceIcon.ConnectorPlate, "connectorPlate"},
			{eKrangAtHomeSourceIcon.Contrast, "contrast"},
			{eKrangAtHomeSourceIcon.Dashboard, "dashboard"},
			{eKrangAtHomeSourceIcon.Delete, "delete"},
			{eKrangAtHomeSourceIcon.DeleteAlt, "deleteAlt"},
			{eKrangAtHomeSourceIcon.DirecTv, "direcTV"},
			{eKrangAtHomeSourceIcon.Disk, "disk"},
			{eKrangAtHomeSourceIcon.Dnd, "dnd"},
			{eKrangAtHomeSourceIcon.DndOn, "dndON"},
			{eKrangAtHomeSourceIcon.Door, "door"},
			{eKrangAtHomeSourceIcon.Down, "down"},
			{eKrangAtHomeSourceIcon.DownAlt, "downAlt"},
			{eKrangAtHomeSourceIcon.Download, "download"},
			{eKrangAtHomeSourceIcon.DownloadCloud, "downloadCloud"},
			{eKrangAtHomeSourceIcon.Drapes, "drapes"},
			{eKrangAtHomeSourceIcon.Dvd, "dvd"},
			{eKrangAtHomeSourceIcon.Eject, "eject"},
			{eKrangAtHomeSourceIcon.Enter, "enter"},
			{eKrangAtHomeSourceIcon.Erase, "erase"},
			{eKrangAtHomeSourceIcon.Eye, "eye"},
			{eKrangAtHomeSourceIcon.Film, "film"},
			{eKrangAtHomeSourceIcon.Fire, "fire"},
			{eKrangAtHomeSourceIcon.Fireplace, "fireplace"},
			{eKrangAtHomeSourceIcon.Folder, "folder"},
			{eKrangAtHomeSourceIcon.Fwd, "fwd"},
			{eKrangAtHomeSourceIcon.Games, "games"},
			{eKrangAtHomeSourceIcon.Garage, "garage"},
			{eKrangAtHomeSourceIcon.Gear, "gear"},
			{eKrangAtHomeSourceIcon.Globe, "globe"},
			{eKrangAtHomeSourceIcon.Graph, "graph"},
			{eKrangAtHomeSourceIcon.GraphAlt, "graphAlt"},
			{eKrangAtHomeSourceIcon.Grid, "grid"},
			{eKrangAtHomeSourceIcon.Guide, "guide"},
			{eKrangAtHomeSourceIcon.Hd, "hd"},
			{eKrangAtHomeSourceIcon.Heart, "heart"},
			{eKrangAtHomeSourceIcon.Help, "help"},
			{eKrangAtHomeSourceIcon.Home, "home"},
			{eKrangAtHomeSourceIcon.HotTub, "hotTub"},
			{eKrangAtHomeSourceIcon.Image, "image"},
			{eKrangAtHomeSourceIcon.Info, "info"},
			{eKrangAtHomeSourceIcon.Ipad, "ipad"},
			{eKrangAtHomeSourceIcon.Iphone, "iphone"},
			{eKrangAtHomeSourceIcon.Ipod, "ipod"},
			{eKrangAtHomeSourceIcon.Keyboard, "keyboard"},
			{eKrangAtHomeSourceIcon.Keypad, "keypad"},
			{eKrangAtHomeSourceIcon.Laptop, "laptop"},
			{eKrangAtHomeSourceIcon.LastFm, "lastFM"},
			{eKrangAtHomeSourceIcon.Left, "left"},
			{eKrangAtHomeSourceIcon.LeftAlt, "leftAlt"},
			{eKrangAtHomeSourceIcon.Link, "link"},
			{eKrangAtHomeSourceIcon.Lights, "lights"},
			{eKrangAtHomeSourceIcon.LightsOff, "lightsOff"},
			{eKrangAtHomeSourceIcon.List, "list"},
			{eKrangAtHomeSourceIcon.Live, "live"},
			{eKrangAtHomeSourceIcon.Location, "location"},
			{eKrangAtHomeSourceIcon.LocationMinus, "locationMinus"},
			{eKrangAtHomeSourceIcon.LocationPlus, "locationPlus"},
			{eKrangAtHomeSourceIcon.LockLocked, "locked"},
			{eKrangAtHomeSourceIcon.LockUnlocked, "unlocked"},
			{eKrangAtHomeSourceIcon.MediaServer, "mediaServer"},
			{eKrangAtHomeSourceIcon.MicMute, "micMute"},
			{eKrangAtHomeSourceIcon.MicMuted, "micMuted"},
			{eKrangAtHomeSourceIcon.Minus, "minus"},
			{eKrangAtHomeSourceIcon.More, "more"},
			{eKrangAtHomeSourceIcon.Mouse, "mouse"},
			{eKrangAtHomeSourceIcon.MultiUsers, "multiUsers"},
			{eKrangAtHomeSourceIcon.Next, "next"},
			{eKrangAtHomeSourceIcon.NextPage, "nextPage"},
			{eKrangAtHomeSourceIcon.OptionsOff, "optionsOff"},
			{eKrangAtHomeSourceIcon.OptionsOn, "optionsOn"},
			{eKrangAtHomeSourceIcon.Outlet, "outlet"},
			{eKrangAtHomeSourceIcon.Pandora, "pandora"},
			{eKrangAtHomeSourceIcon.Pause, "pause"},
			{eKrangAtHomeSourceIcon.Phone, "phone"},
			{eKrangAtHomeSourceIcon.PhoneDown, "phoneDown"},
			{eKrangAtHomeSourceIcon.Play, "play"},
			{eKrangAtHomeSourceIcon.PlayAll, "playAll"},
			{eKrangAtHomeSourceIcon.PlayAlt, "playAlt"},
			{eKrangAtHomeSourceIcon.PlayLibrary, "playLibrary"},
			{eKrangAtHomeSourceIcon.Playlist, "playlist"},
			{eKrangAtHomeSourceIcon.PlaylistAlt, "playlistAlt"},
			{eKrangAtHomeSourceIcon.PlayPause, "playPause"},
			{eKrangAtHomeSourceIcon.Plus, "plus"},
			{eKrangAtHomeSourceIcon.Pool, "pool"},
			{eKrangAtHomeSourceIcon.Power, "power"},
			{eKrangAtHomeSourceIcon.Previous, "previous"},
			{eKrangAtHomeSourceIcon.PreviousPage, "prevPage"},
			{eKrangAtHomeSourceIcon.Projector, "projector"},
			{eKrangAtHomeSourceIcon.RecWeb, "recWeb"},
			{eKrangAtHomeSourceIcon.Repeat, "repeat"},
			{eKrangAtHomeSourceIcon.RepeatItem, "repeatItem"},
			{eKrangAtHomeSourceIcon.RepeatOff, "repeatOff"},
			{eKrangAtHomeSourceIcon.Replay, "replay"},
			{eKrangAtHomeSourceIcon.Rhapsody, "rhapsody"},
			{eKrangAtHomeSourceIcon.Right, "right"},
			{eKrangAtHomeSourceIcon.RightAlt, "RightAlt"},
			{eKrangAtHomeSourceIcon.Rss, "rss"},
			{eKrangAtHomeSourceIcon.Rwd, "rwd"},
			{eKrangAtHomeSourceIcon.Satellite, "satellite"},
			{eKrangAtHomeSourceIcon.Search, "search"},
			{eKrangAtHomeSourceIcon.Settings, "settings"},
			{eKrangAtHomeSourceIcon.Shades, "shades"},
			{eKrangAtHomeSourceIcon.Share, "share"},
			{eKrangAtHomeSourceIcon.Shield, "shield"},
			{eKrangAtHomeSourceIcon.Shuffle, "shuffle"},
			{eKrangAtHomeSourceIcon.ShuffleItem, "shuffleItem"},
			{eKrangAtHomeSourceIcon.ShuffleOff, "shuffleOff"},
			{eKrangAtHomeSourceIcon.Signal, "signal"},
			{eKrangAtHomeSourceIcon.Sirius, "sirius"},
			{eKrangAtHomeSourceIcon.SiriusXm, "siriusXM"},
			{eKrangAtHomeSourceIcon.Slow, "slow"},
			{eKrangAtHomeSourceIcon.Snowflake, "snowflake"},
			{eKrangAtHomeSourceIcon.SongAdd, "songAdd"},
			{eKrangAtHomeSourceIcon.Spotify, "spotify"},
			{eKrangAtHomeSourceIcon.Star, "star"},
			{eKrangAtHomeSourceIcon.Stop, "stop"},
			{eKrangAtHomeSourceIcon.Stopwatch, "stopwatch"},
			{eKrangAtHomeSourceIcon.Sun, "sun"},
			{eKrangAtHomeSourceIcon.System, "system"},
			{eKrangAtHomeSourceIcon.Theater, "theater"},
			{eKrangAtHomeSourceIcon.ThumbsDown, "thumbsDown"},
			{eKrangAtHomeSourceIcon.ThumbsUp, "thumbsUp"},
			{eKrangAtHomeSourceIcon.Trash, "trash"},
			{eKrangAtHomeSourceIcon.Triangle, "triangle"},
			{eKrangAtHomeSourceIcon.Tv, "tv"},
			{eKrangAtHomeSourceIcon.Up, "up"},
			{eKrangAtHomeSourceIcon.UpAlt, "upAlt"},
			{eKrangAtHomeSourceIcon.Upload, "upload"},
			{eKrangAtHomeSourceIcon.Usb, "usb"},
			{eKrangAtHomeSourceIcon.UsbAlt, "usbAlt"},
			{eKrangAtHomeSourceIcon.User, "user"},
			{eKrangAtHomeSourceIcon.UserAdd, "userAdd"},
			{eKrangAtHomeSourceIcon.UserCheck, "userCheck"},
			{eKrangAtHomeSourceIcon.UserMinus, "userMinus"},
			{eKrangAtHomeSourceIcon.VideoInput, "videoInput"},
			{eKrangAtHomeSourceIcon.VideoOuptut, "videoOutput"},
			{eKrangAtHomeSourceIcon.VideoScreen, "videoScreen"},
			{eKrangAtHomeSourceIcon.VolumeDown, "volumeDown"},
			{eKrangAtHomeSourceIcon.VolumeMute, "volumeMute"},
			{eKrangAtHomeSourceIcon.VolumeUp, "volumeUp"},
			{eKrangAtHomeSourceIcon.Weather, "weather"},
			{eKrangAtHomeSourceIcon.Wifi, "wifi"},
			{eKrangAtHomeSourceIcon.Windows, "windows"},
			{eKrangAtHomeSourceIcon.WirelessDevice, "wirelessDevice"},
			{eKrangAtHomeSourceIcon.Wrench, "wrench"},
			{eKrangAtHomeSourceIcon.Write, "write"},
			{eKrangAtHomeSourceIcon.Xm, "xm"}
		};


		public static string GetStringForIcon(this eKrangAtHomeSourceIcon icon, bool active)
		{
			return GetStringForIcon((eKrangAtHomeSourceIcon?)icon, active);
		}


		public static string GetStringForIcon(this eKrangAtHomeSourceIcon? icon, bool active)
		{
			if (!icon.HasValue)
				return TRANSPARENT_ICON_SERIAL;

			StringBuilder serial = new StringBuilder();
			serial.Append("si_");

			string iconSpecificSerial;
			if (!s_IconSerials.TryGetValue(icon.Value, out iconSpecificSerial))
				throw new ArgumentOutOfRangeException("icon", String.Format("No mapping of type {0} to string", icon));
			serial.Append(iconSpecificSerial);

			serial.Append(active ? "_black" : "_white");

			return serial.ToString();
		}
	}
}